application: number-pitch
version: 1
runtime: php
threadsafe: true
api_version: 1

handlers:
- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /fonts
  static_dir: fonts

- url: /index\.html
  static_files: index.html
  upload: index.html

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon.ico

- url: /
  static_files: index.html
  upload: index.html
